# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmtvEZaA9Cixqsnp4JfZpEPdewt40ho6
"""

import math
import matplotlib.pyplot as plt
import pandas as pd

def f(x):
    return (1 / math.sqrt(900 - x**2)) + (1 / math.sqrt(400 - x**2)) - 0.125

def bissecao(a, b, tol=0.01):
    iteracoes = []
    k = 1

    while (b - a) >= tol:
        x = (a + b) / 2.0
        fx = f(x)
        iteracoes.append({
            "k": k, "a": a, "b": b, "x = (a+b)/2": x,
            "f(x)": fx, "b - a": b - a, "Novo Intervalo": f"[{a:.6f}; {b:.6f}]"
        })
        if f(a) * fx < 0:
            b = x
        else:
            a = x
        k += 1

    x = (a + b) / 2.0
    fx = f(x)
    iteracoes.append({
        "k": k, "a": a, "b": b, "x = (a+b)/2": x,
        "f(x)": fx, "b - a": b - a, "Novo Intervalo": f"[{a:.6f}; {b:.6f}]"
    })
    return pd.DataFrame(iteracoes)

df_bissecao = bissecao(16.0, 17.0, tol=0.01)

print("=== MÉTODO DA BISSEÇÃO ===")
display(df_bissecao.style.format({
    "a": "{:.6f}", "b": "{:.6f}", "x = (a+b)/2": "{:.6f}",
    "f(x)": "{:.6f}", "b - a": "{:.6f}"
}))

plt.figure(figsize=(8, 4))
plt.plot(df_bissecao["k"], df_bissecao["x = (a+b)/2"], 'o-', color='#1f77b4', linewidth=2, label='x_k')
plt.axhline(y=16.2121, color='r', linestyle='--', alpha=0.7, label='Valor Exato (~16.2121 m)')
plt.title('Convergência - Método da Bisseção', fontsize=12, fontweight='bold')
plt.xlabel('Iteração (k)')
plt.ylabel('Largura x (m)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import math
import matplotlib.pyplot as plt
import pandas as pd

def f(x):
    return (1 / math.sqrt(900 - x**2)) + (1 / math.sqrt(400 - x**2)) - 0.125

def posicao_falsa(a, b, max_iter=7):
    iteracoes = []
    for k in range(1, max_iter + 1):
        fa, fb = f(a), f(b)
        x = (a * fb - b * fa) / (fb - fa)
        fx = f(x)
        iteracoes.append({"k": k, "a_k": a, "b_k": b, "f(a_k)": fa, "f(b_k)": fb, "x_k": x, "f(x_k)": fx})
        if fa * fx < 0:
            b = x
        else:
            a = x
    return pd.DataFrame(iteracoes)

df_posicao_falsa = posicao_falsa(10.0, 18.0, max_iter=7)

print("=== MÉTODO DA POSIÇÃO FALSA ===")
display(df_posicao_falsa.style.format("{:.6f}", subset=["a_k", "b_k", "f(a_k)", "f(b_k)", "x_k", "f(x_k)"]))

plt.figure(figsize=(8, 4))
plt.plot(df_posicao_falsa["k"], df_posicao_falsa["x_k"], 's-', color='#ff7f0e', linewidth=2, label='x_k')
plt.axhline(y=16.2121, color='r', linestyle='--', alpha=0.7, label='Valor Exato (~16.2121 m)')
plt.title('Convergência - Método da Posição Falsa', fontsize=12, fontweight='bold')
plt.xlabel('Iteração (k)')
plt.ylabel('Largura x (m)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import math
import matplotlib.pyplot as plt
import pandas as pd

def a_func(x):
    return math.sqrt(900 - x**2)

def b_func(x):
    return (0.125 - (900 - x**2)**(-0.5))**(-1)

def g(x):
    return math.sqrt(400 - (b_func(x))**2)

def ponto_fixo(x0, max_iter=6):
    iteracoes = []
    x_k = x0
    for k in range(max_iter):
        a_k, b_k = a_func(x_k), b_func(x_k)
        x_next = g(x_k)
        erro = abs(x_next - x_k)
        iteracoes.append({"k": k, "x_k": x_k, "a(x_k)": a_k, "b(x_k)": b_k, "x_{k+1}": x_next, "|x_{k+1} - x_k|": erro})
        x_k = x_next
    return pd.DataFrame(iteracoes)

df_ponto_fixo = ponto_fixo(15.0, max_iter=6)

print("=== MÉTODO ITERATIVO LINEAR (PONTO FIXO) ===")
display(df_ponto_fixo.style.format("{:.6f}", subset=["x_k", "a(x_k)", "b(x_k)", "x_{k+1}", "|x_{k+1} - x_k|"]))

plt.figure(figsize=(8, 4))
plt.plot(df_ponto_fixo["k"], df_ponto_fixo["x_k"], 'd-', color='#2ca02c', linewidth=2, label='x_k')
plt.axhline(y=16.2121, color='r', linestyle='--', alpha=0.7, label='Valor Exato (~16.2121 m)')
plt.title('Convergência - Método Iterativo Linear', fontsize=12, fontweight='bold')
plt.xlabel('Iteração (k)')
plt.ylabel('Largura x (m)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import math
import matplotlib.pyplot as plt
import pandas as pd

def f(x):
    return (900 - x**2)**(-0.5) + (400 - x**2)**(-0.5) - 0.125

def secantes(x0, x1, max_iter=6):
    iteracoes = []
    iteracoes.append({"k": 0, "x_k": x0, "f(x_k)": f(x0), "x_{k+1}": x1, "|x_{k+1} - x_k|": abs(x1 - x0)})
    for k in range(1, max_iter):
        fx0, fx1 = f(x0), f(x1)
        x_next = x1 - fx1 * ((x1 - x0) / (fx1 - fx0))
        erro = abs(x_next - x1)
        iteracoes.append({"k": k, "x_k": x1, "f(x_k)": fx1, "x_{k+1}": x_next, "|x_{k+1} - x_k|": erro})
        x0, x1 = x1, x_next
    return pd.DataFrame(iteracoes)

df_secantes = secantes(15.0, 17.0, max_iter=6)

print("=== MÉTODO DAS SECANTES ===")
display(df_secantes.style.format("{:.6f}", subset=["x_k", "f(x_k)", "x_{k+1}", "|x_{k+1} - x_k|"]))

plt.figure(figsize=(8, 4))
plt.plot(df_secantes["k"], df_secantes["x_k"], '^-', color='#9467bd', linewidth=2, label='x_k')
plt.axhline(y=16.2121, color='r', linestyle='--', alpha=0.7, label='Valor Exato (~16.2121 m)')
plt.title('Convergência - Método das Secantes', fontsize=12, fontweight='bold')
plt.xlabel('Iteração (k)')
plt.ylabel('Largura x (m)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import math
import matplotlib.pyplot as plt
import pandas as pd

def f(x):
    return (900 - x**2)**(-0.5) + (400 - x**2)**(-0.5) - 0.125

def df(x):
    return (x / (900 - x**2)**(1.5)) + (x / (400 - x**2)**(1.5))

def newton_raphson(x0, max_iter=4):
    iteracoes = []
    x_k = x0
    for k in range(max_iter):
        fx, dfx = f(x_k), df(x_k)
        x_next = x_k - (fx / dfx)
        erro = abs(x_next - x_k)
        iteracoes.append({"k": k, "x_k": x_k, "f(x_k)": fx, "f'(x_k)": dfx, "x_{k+1}": x_next, "|x_{k+1} - x_k|": erro})
        x_k = x_next
    return pd.DataFrame(iteracoes)

df_newton = newton_raphson(15.0, max_iter=4)

print("=== MÉTODO DE NEWTON-RAPHSON ===")
display(df_newton.style.format("{:.6f}", subset=["x_k", "f(x_k)", "f'(x_k)", "x_{k+1}", "|x_{k+1} - x_k|"]))

plt.figure(figsize=(8, 4))
plt.plot(df_newton["k"], df_newton["x_k"], 'p-', color='#d62728', linewidth=2, label='x_k')
plt.axhline(y=16.2121, color='black', linestyle='--', alpha=0.7, label='Valor Exato (~16.2121 m)')
plt.title('Convergência Quadrática - Newton-Raphson', fontsize=12, fontweight='bold')
plt.xlabel('Iteração (k)')
plt.ylabel('Largura x (m)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()